### PR TITLE
Vote to allow or disallow teamoverlay

### PR DESCRIPTION
**Pull request by JosephPecoraro**
I could only test this on localhost but it follows nospecs quite closely. Let me know if you want me to clean up the formatting. The whitespace is pretty unbearable.

### CODE REVIEW

**Comment by JosephPecoraro** [comment]
Tested:
* Less than 2 players in server => vote does nothing
* Two players toggles server setting when > 50% of votes
* /whovote functionality correctly identifies voters for the correct property

ingame-checks

**Comment by jite** [comment]
If you're alone on the server you should be able to toggle. Thats how every other votable command works IIRC.

**Comment by JosephPecoraro** [comment]
That is not how /rpickup or /nospecs worked, so I followed the existing pattern. I think it makes sense to wait for 2 players, the server default is already on and I'd rather promote the default be on.

**Comment by JosephPecoraro** [comment]
Bump.

**Pull request merged**
