### PR TITLE
Fixing issue #74: coach privilege is not preserved during map reload

### PR DESCRIPTION
**Pull request by tcsabina**

### CODE REVIEW

**Comment by tcsabina** [comment]
deurk,
there are 2 commits, each tackling a separate issue.
I would rather separate them into separate PR, but it seems it is not trivial in github (I would need separate branch for each issue...)
Let me know how you would like to see them.

**Comment by deurk** [comment]
I would love to have 2 separate PR if you can manage it. Otherwise I'll replicate the changes on my side, no worries just let me know.

**Comment by deurk** [comment]
I realize I forgot to credit you @tcsabina for the changes I've included in the latest commits... I'm sorry about that, but thank you, all has been merged into current code base.

**Comment by tcsabina** [comment]
Hi deurk,
no problem ;)!

what is important is that the community benefits :D

Regards,
toma

**Pull request closed without merging**
